version: "3"
# --------------------------------------Production----Docker-----------------------------------------------------

# services:
#     lms_pma:
#         image: phpmyadmin/phpmyadmin
#         container_name: lms_pma
#         restart: unless-stopped
#         environment:
#             PMA_HOST: library-database.cn2k6gkoqxb1.ap-south-1.rds.amazonaws.com
#             PMA_PORT: 3306
#             PMA_USER: ScottLang
#             PMA_PASSWORD: AntMan#321
#             PMA_ABSOLUTE_URI: http://localhost:8081
#         ports:
#             - 8081:80
# volumes:
#     dbdata:

# --------------------------------------Development----Docker-----------------------------------------------------

# services:
#     lms_db:
#         image: mysql:latest
#         container_name: lms_db
#         restart: unless-stopped
#         environment:
#             MYSQL_ROOT_PASSWORD: root_password
#             MYSQL_DATABASE: library
#             MYSQL_USER: user
#             MYSQL_PASSWORD: password
#         ports:
#             - "3306:3306"
#         volumes:
#             - dbdata:/var/lib/mysql
#     lms_pma:
#         image: phpmyadmin/phpmyadmin
#         container_name: lms_pma
#         restart: unless-stopped
#         links:
#             - lms_db
#         environment:
#             PMA_HOST: lms_db
#             PMA_PORT: 3306
#             # PMA_ARBITRARY: 1
#         ports:
#             - 8080:80
# volumes:
#     dbdata:
 